accounts/urls.py
from django.urls import path
from .views import CustomLoginView, CustomLogoutView, CustomRegisterView
app_name = 'accounts'

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('register/', CustomRegisterView.as_view(), name='register')
]

articles/urls.py
from django.urls import path
from .views import ArticlesListView, ArticleDetailView, ArticleCreateView, ArticleUpdateView, ArticleDeleteView
from django.conf import settings
from django.conf.urls.static import static

app_name = 'articles'

urlpatterns = [
    path('', ArticlesListView.as_view(), name='all-articles'),
    path('create-article/', ArticleCreateView.as_view(), name='create-article'),
    path('<slug:slug>', ArticleDetailView.as_view(), name='article'),
    path('edit-article/<slug:slug>', ArticleUpdateView.as_view(), name='edit-article'),
    path('delete-article/<slug:slug>', ArticleDeleteView.as_view(), name='delete-article')
]

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL,
#                           document_root=settings.MEDIA_ROOT)

blog_app/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.views.static import serve
from django.conf import settings
from .views import homepage

urlpatterns = [
    re_path('r^media/(?P<path>.*)$', serve,
            {'documentroot': settings.MEDIA_ROOT}),
    re_path('r^static/(?P<path>.*)$', serve,
            {'documentroot': settings.STATIC_ROOT}),
    path('admin/', admin.site.urls),
    path('', homepage, name='home'),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.db.models.signals import pre_save, post_delete
from uuid import uuid4
from django.contrib.auth.models import AbstractUser
from django.dispatch import receiver
from .manager import UserManager
# Create your models here.


class CustomUser(AbstractUser):
    username = models.CharField(max_length=100, unique=True, blank=True)
    id = models.UUIDField(primary_key=True, default=uuid4, editable=False)
    email = models.EmailField(max_length=254, unique=True)
    bio = models.TextField(max_length=100, blank=True)
    profile_image = models.ImageField(blank=True, default='placeholder-pfp.jpg')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']
    objects = UserManager()

    def __str__(self):
        return self.username

    

articles/models.py
from django.db import models
from django.db.models.signals import pre_save, post_delete
from uuid import uuid4
import os
from django.utils.text import slugify
from django.dispatch import receiver
from django.conf import settings
from django.contrib.auth import get_user_model
User = get_user_model()

# Create your models here.


class ArticleModel(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid4, editable=False)
    title = models.CharField(max_length=60, null=False)
    description = models.CharField(max_length=150, blank=True)
    image = models.ImageField(blank=True)
    content = models.TextField(null=False)
    slug = models.SlugField(default='', blank=True)
    author = models.ForeignKey(User, null=False, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            slug_title = slugify(self.title)
            self.slug = f'{slug_title}-{self.id}'

        super().save(*args, **kwargs)


@receiver(pre_save, sender=ArticleModel)
def delete_old_image(sender, instance, **kwargs):
    if instance.id:
        try:
            old_instance = ArticleModel.objects.get(id=instance.id)
        except ArticleModel.DoesNotExist:
            return
        if old_instance.image:
            old_image_path = os.path.join(
                settings.MEDIA_ROOT, str(old_instance.image))
            if os.path.exists(old_image_path):
                os.remove(old_image_path)


@receiver(post_delete, sender=ArticleModel)
def delete_image(sender, instance, **kwargs):
    if instance.image:
        image_path = os.path.join(settings.MEDIA_ROOT, str(instance.image))
        if os.path.exists(image_path):
            os.remove(image_path)

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import CustomUser
from django.core.exceptions import ValidationError


class CustomUserForm(UserCreationForm):
    email = forms.EmailField(required=True)
    password1 = forms.CharField(
        required=True,
        label="Password",
        widget=forms.PasswordInput,
        help_text="Enter a strong password.Use A-Z, a-z, special cahracters like @ etc. and numbers."
    )
    password2 = forms.CharField(
        required=True,
        label="Confirm password",
        widget=forms.PasswordInput,
        help_text="Enter same passowrd as above"
    )

    class Meta:
        model = CustomUser
        fields = ['email', 'username', 'password1', 'password2']

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise ValidationError('Passwords do not match.')
        return password2

accounts/views.py
from django.urls import reverse_lazy
from django.shortcuts import redirect
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth import login
from django.views.generic import FormView
from .forms import CustomUserForm
# Create your views here.


class CustomLoginView(LoginView):
    template_name = 'accounts/login.html'
    fields = '__all__'
    redirect_authenticated_user = True

    def get_success_url(self):
        return reverse_lazy('articles:all-articles')


class CustomLogoutView(LogoutView):
    next_page = 'accounts:login'


class CustomRegisterView(FormView):
    template_name = 'accounts/register.html'
    form_class = CustomUserForm
    redirect_authenticated_user = True
    success_url = reverse_lazy('articles:all-articles')

    def form_valid(self, form):
        user = form.save()
        if user is not None:
            login(self.request, user)
            return super(CustomRegisterView, self).form_valid(form)

    def get(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect('articles:all-articles')
        return super(CustomRegisterView, self).get(*args, **kwargs)

articles/views.py
from .models import ArticleModel
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.core.exceptions import PermissionDenied


# Create your views here.


class ArticlesListView(ListView):
    model = ArticleModel
    context_object_name = 'articles'
    template_name = 'articles/all_articles.html'


class ArticleDetailView(DetailView):
    model = ArticleModel
    context_object_name = 'article'
    template_name = 'articles/article_detail.html'


class ArticleCreateView(LoginRequiredMixin, CreateView):
    model = ArticleModel
    fields = ['title', 'description', 'image', 'content']
    success_url = reverse_lazy('articles:all-articles')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class ArticleUpdateView(LoginRequiredMixin, UpdateView):
    model = ArticleModel
    fields = ['title', 'description', 'image', 'content']

    def get_success_url(self):
        return reverse_lazy('articles:article', kwargs={'slug': self.object.slug})

    def get_object(self, queryset=None):
        article = super().get_object(queryset)

        if article.author != self.request.user:
            raise PermissionDenied(
                'Do not have permission to change this article\'s contents')
        return article


class ArticleDeleteView(LoginRequiredMixin, DeleteView):
    model = ArticleModel
    context_object_name = 'article'
    template_name = 'articles/delete_form.html'
    success_url = reverse_lazy('articles:all-articles')

    def get_object(self, queryset=None):
        article = super().get_object(queryset)

        if article.author != self.request.user:
            raise PermissionDenied(
                'Do not have permission to change this article\'s contents')
        return article

blog_app/views.py
from django.shortcuts import render

def homepage(request):
    return render(request, 'home.html')

accounts/templates/accounts/login.html
{% extends "layout.html" %}
{% block title %}Login{% endblock title %}

{% block content %}
<h1 class='primary-text'>Login</h1>
<form class="validated-form" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input  class="secondary-btn" type="submit" value="Login">
</form>
{% endblock content %}

accounts/templates/accounts/register.html
{% extends "layout.html" %}
{% block title %}Title{% endblock title %}
{% block content %}
<form class="validated-form" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input class="secondary-btn" type="submit" value="Submit">
</form>
{% endblock content %}

articles/templates/articles/all_articles.html
{% extends "layout.html" %}
{% block title %}All Articles{% endblock title %}
{% block content %}
<h1 class="primary-text">All Articles</h1>
{% for article in articles%}
<div class='article'>
    <div class="article-contents">
        <p class="secondary-text">{{article.author}}</p>
        <h2 class="primary-text"><a class="primary-text" href="{% url "articles:article" article.slug %}">{{article.title}}</a></h2>
        <p class="secondary-text">{{article.description}}</p>
    </div>
  <a class="secondary-text" href="{% url "articles:article" article.slug %}">Read post ➡️</a> 
</div>
<hr class="divider">
{% endfor %}
{% endblock content %}

articles/templates/articles/article_detail.html
{% extends "layout.html" %}
{% block title %}{{article.title}}{% endblock title %}

{% block content %}
<a class="secondary-text" href="{% url 'articles:all-articles'%}">⬅️ back to all articles</a>
<div class="article-data">
    <p class="secondary-text">{{article.author}}</p>
    <p class="secondary-text">{{article.created_at}}</p>
</div>
{% if request.user == article.author %}
<div class="actions">
    <a class="secondary-text" href="{% url 'articles:edit-article' article.slug %}">📝 edit</a>
    <i class="secondary-text">||</i>
    <a class="secondary-text"href="{% url 'articles:delete-article' article.slug %}">🗑️ delete</a>
</div>
{% endif %}
<h1 class="primary-text">{{article.title}}</h1>
{% if article.description %}
    <h3 class="secondary-text">{{article.description}}</h3>
{% endif %}


{% if article.image %}
    <img class="article-image" src="{{article.image.url}}" alt="{{article.title}}">
{% endif %}
<p class="secondary-text">{{article.content}}</p>
{% endblock content %}

articles/templates/articles/articlemodel_form.html
{% extends "layout.html" %}
{% block title %}Write your own{% endblock title %}
{% block content %}
<div>
     {% if object.slug %}
            <a class="secondary-text" href="{% url 'articles:article' object.slug %}">⬅️ Back</a>
        {% else %}
            <a class="secondary-text" href="{% url 'articles:all-articles'%}">❌ Cancel</a>
        {% endif %}
   <div>
        <h1 class="primary-text">Create Articles</h1>
       
        <form class="validated-form" method='post' enctype="multipart/form-data">
            {%csrf_token%}
            {{form.as_p}}
            <input class="submit-btn" type="submit" value="Submit">
        </form>
   </div>
</div>
{% endblock content %}

articles/templates/articles/delete_form.html
{% extends "layout.html" %}
{% block title %}{{object.title}}{% endblock title %}
{% block content %}
<a class="secondary-text" href="{% url 'articles:article' object.slug %}">❌ Cancel</a>
<h1 class="primary-text">Delete Article {{object.title}} ?</h1>
<form class="delete-form" method='post'>
    {% csrf_token %}
    <input type="submit" value="Submit">
</form>
{% endblock content %}

templates/home.html
{% extends 'layout.html' %}
{% block title %}Home{% endblock title %}
{% block content %}
<h1>Home Page</h1>
{% endblock content %}

templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Blog</title>
    <link rel="stylesheet" href="{% static 'styles/styles.css' %}">
</head>
<body>
    <nav>
        <h1><a class="logo" href="{% url 'home' %}">My blog</a></h1>
        <div>
            <a class="nav-links" href="{% url 'articles:all-articles'%}">All Articles</a>
            {% if request.user.is_authenticated %}
                     <a class="nav-links" href="{% url 'articles:create-article' %}">Write your blog ...</a>
            {% endif %}
            <a class="nav-links" href="">About</a>
        </div>
        <div>
            {% if request.user.is_authenticated %} 
                <form class="logout-form" action="{% url 'accounts:logout' %}" method="post">
                    {% csrf_token %}
                    <input class="primary-btn" type="submit" value="Logout">
                </form>
            {% else %}
                <a class="secondary-btn" href="{% url 'accounts:login' %}">Login </a>
                <a class="primary-btn" href="{% url "accounts:register" %}">Register</a>
            {% endif %}
           
        </div>
    </nav>
    <main>
       <section> {% block content %}{% endblock content %}</section>
    </main>
</body>
</html>